#!/usr/bin/python

import os
import sys
import imp

imp.load_source("tmt", sys.path[0]+"/../../tmt")

files = os.popen("git diff --name-only").read().split('\n')
files = filter(lambda f: f.endswith('.js'), files)
for f in files:
	#success = os.system("ant -f timer/build.xml jslint")

	# TODO - returning 256 is treated as success?
	if success != 0:
		sys.exit("Failed jslint. Use git commit --no-verify if you really know what you're doing.")
