export const ActionTypes = {
    UPDATE_ME: "UPDATE_ME",
    UPDATE_EVENTS: "UPDATE_EVENTS",
    UPDATE_PASSWORD: "UPDATE_PASSWORD",
    UPDATE_COMPETITION_NAME: "UPDATE_COMPETITION_NAME",
    UPDATE_WCA_EVENT: "UPDATE_WCA_EVENT",
    UPDATE_MBLD: "UPDATE_MBLD",
    UPDATE_COMPETITIONS: "UPDATE_COMPETITIONS",
    UPDATE_COMPETITION_ID: "UPDATE_COMPETITION_ID",
    UPDATE_WCIF: "UPDATE_WCIF",
    UPDATE_EDITING_STATUS: "UPDATE_EDITING_STATUS"
};
