export const ActionTypes = {
  UPDATE_ME: "UPDATE_ME",
  UPDATE_WCIF: "UPDATE_WCIF",
  UPDATE_PASSWORD: "UPDATE_PASSWORD",
  UPDATE_COMPETITION_NAME: "UPDATE_COMPETITION_NAME",
  UPDATE_WCA_EVENT: "UPDATE_WCA_EVENT"
};
