#!/bin/sh

if [ $# -lt 2 ]
then
        echo "USAGE: `basename $0` PIDFILE COMMAND [ARGS...]"
        exit 1
fi

# you can't fg inside of a script unless you enable montior mode
# see "man bash" and search for "monitor"
set -o monitor

PIDFILE="$1" # the first command line argument is the file we are to write the pid to
shift
"$@" & # execute the rest of the command line arguments in the background
echo $! > "$PIDFILE"
fg
rm $PIDFILE
