#!/usr/bin/python

import tmt

class Project(tmt.TmtProject):
	def compile(self):
		tmt.TmtProject.projects['timer'].compile();
	
	def getDependencies(self):
		return [ tmt.TmtProject.projects['timer'] ]

	def check(self):
		return
	
	def clean(self):
		tmt.TmtProject.projects['timer'].clean()

Project(tmt.projectName())
