#!/usr/bin/python

import tmt

class Project(tmt.TmtProject):
	def compile(self):
		for project in tmt.TmtProject.projects.values():
			if project == self:
				continue
			project.compile()
	
	def getDependencies(self):
		return [ tmt.TmtProject.projects['timer'] ]

	def check(self):
		return
	
	def clean(self):
		for project in tmt.TmtProject.projects.values():
			if project == self:
				continue
			project.clean()
Project('all')
