#!/usr/bin/python

import tmt

class Project(tmt.EclipseProject):
	def __init__(self):
		tmt.EclipseProject.__init__(
				self,
				tmt.projectName(),
				main='net.gnehzr.tnoodle.scrambles.Main',
				tests=['net.gnehzr.tnoodle.test.ScrambleTest'])

	def configure(self):
		tmt.EclipseProject.configure(self)
		self.nonJavaSrcDeps += tmt.glob(self.srcResource, '.*png$', relativeTo=self.srcResource)
		self.nonJavaSrcDeps.append('scrambler/scramblers')

Project()
