#!/usr/bin/python

import tmt
import subprocess
from os.path import join, exists

class Project(tmt.EclipseProject):
	def configure(self):
		tmt.EclipseProject.configure(self)
		self.transition_tables = join(self.bin, 'org/squareone/twophase/transition_tables')
		self.shape_table = join(self.bin, 'org/squareone/twophase/shape_table')
		self.perm_table = join(self.bin, 'org/squareone/twophase/perm_table')

	def compile(self):
		tmt.EclipseProject.compile(self)
		# build the tables for the two phase algorithm
		# if they don't already exist
		if not exists(self.transition_tables) or not exists(self.shape_table) or not exists(self.perm_table):
			assert 0 == tmt.java(
							main="org.squareone.twophase.Tables",
							classpath=self.getClasspath(),
							args=[ self.transition_tables, self.shape_table, self.perm_table ])

Project('squareone')
