#!/usr/bin/python

import tmt
import os
from os.path import join, exists, relpath
import shutil

SERVER_PLUGIN_DIR = 'serverPlugins'
CONTEXT_FILE = 'context'

class Project(tmt.EclipseProject):
	def __init__(self, *args, **kwargs):
		tmt.EclipseProject.__init__(
				self,
				tmt.projectName(),
				main='net.gnehzr.tnoodle.server.TNoodleServer')
		self.plugins = {}

	def addPlugin(self, project):
		project.serverPluginSrcDir = join(project.src, SERVER_PLUGIN_DIR)
		project.contextFileName = join(project.serverPluginSrcDir, CONTEXT_FILE)
		assert exists(join(project.serverPluginSrcDir, project.name))
		project.serverPluginBinDir = join(project.bin, SERVER_PLUGIN_DIR)
		project.serverPluginPackageBinDir = join(project.serverPluginBinDir, project.name)
		project.main = self.main
		assert exists(project.contextFileName)
		assert project.name not in self.plugins
		self.plugins[project.name] = project

	def configure(self):
		tmt.Server = self
		tmt.EclipseProject.configure(self)
		self.addPlugin(self)
		wwwDir = relpath(join(self.serverPluginSrcDir, 'www'), self.src)
		# TODO - add support for globbed stuff to EclipseProject
		#self.nonJavaSrcDeps = tmt.glob(wwwDir, '.*', relativeTo=self.src)
		self.nonJavaSrcDeps = [ wwwDir ]

	def afterCompile(self, compiledProjects):
		context = ''
		for project in self.plugins.values():
			if project not in compiledProjects:
				# If plugin A uses plugin B (which both, of course, use this
				# project), and the developer chooses to compile plugin B, we
				# don't want to load the plugin for A. The compiledProjects
				# argument helps us avoid that.
				continue
			contextFileName = project.contextFileName
			assert exists(contextFileName)

			if project != self:
				linkName = join(self.serverPluginBinDir, project.name)
				dest = relpath(project.serverPluginPackageBinDir, self.serverPluginBinDir)
				linkUpToDate = False
				if os.path.islink(linkName):
					linkTo = os.readlink(linkName)
					if linkTo == dest:
						linkUpToDate = True
				if not linkUpToDate:
					if exists(linkName):
						os.unlink(linkName)
					os.symlink(dest, linkName)

			inputContextFile = file(contextFileName, 'r')
			context += inputContextFile.read() + '\n'

		outputContextFileName = join(self.serverPluginBinDir, CONTEXT_FILE)
		contextFileUpToDate = False
		if exists(outputContextFileName):
			outputContextFile = file(outputContextFileName, 'r')
			contextFileUpToDate = ( outputContextFile.read() == context )
		if not contextFileUpToDate:
			outputContextFile = file(outputContextFileName, 'w')
			outputContextFile.write(context)

Project()
