#!/usr/bin/python

import tmt
import subprocess
import os
from os.path import join, isdir
import shutil
#tmt.parser.add_argument(
	#'--foo', '-f', default='fizzle', type=str, help='testing')

def configure(path):
	global bin, src, dist
	bin = join(path, 'bin')
	src = join(path, 'src')

def compile(path):
	if not isdir(bin):
		os.mkdir(bin)

	lib = join(path, '../lib/gson-1.4.jar') # TODO
	javaFiles = tmt.glob(src, r'.*\.java')
	for javaFile in javaFiles:
		p = subprocess.Popen([ 'javac', '-d', bin, '-classpath', lib, javaFile ])
def dist(path):
	pass
def run(path):
	pass
def clean(path):
	if isdir(bin):
		shutil.rmtree(bin)
