#!/usr/bin/python

import tmt
from os.path import join

class Project(tmt.EclipseProject):
	def configure(self):
		tmt.EclipseProject.configure(self)
		tmt.Server.addPlugin(self)
		self.nonJavaSrcDeps = tmt.glob(self.src, '.*', relativeTo=self.src)

Project('timer')
