#!/usr/bin/python

import tmt
import subprocess
from os.path import join, exists

class Project(tmt.EclipseProject):
	def configure(self):
		tmt.EclipseProject.configure(self)
		self.transition_tables = join(self.bin, 'org/kociemba/twophase/transition_tables')
		self.pruning_tables = join(self.bin, 'org/kociemba/twophase/pruning_tables')

	def afterCompile(self, compiledProjects):
		# build the pruning and transition tables for the two phase algorithm
		# iff they don't already exist
		if not exists(self.transition_tables) or not exists(self.pruning_tables):
			tmt.java(
					main="org.kociemba.twophase.CoordCube",
					classpath=self.getClasspath(),
					args=[ self.transition_tables, self.pruning_tables ])

Project('jcubeexplorer')
